version: '3.8'

services:
  python:
    build: ./app/
    container_name: python-scraper
    restart: always
    depends_on:
      - mysql
    volumes:
      - ./app/main.py:/project/main.py
      - ./app/requirements.txt:/project/requirements.txt
      - ./app/crontab:/etc/cron.d/main-cron
      - ${PATH_ACCESS_LOG}:/project/nginx_logs/access.log
      - ${PATH_ERROR_LOG}:/project/nginx_logs/error.log
      - ./app/app_log/app.log:/var/log/cron.log


# ./fake_logs_for_test/error.log
  mysql:
    image: mysql:8.4.1
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: bp1234
      MYSQL_DATABASE: log_check
    ports:
      - "3309:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 81:80




volumes:
  mysql-data:
